/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
      },
      items: [
        'installation/git',
        'installation/binary',
        'installation/docker',
        'installation/helm',
      ],
    },
    {
      type: 'category',
      label: 'Ingestion',
      link: {
        type: 'generated-index',
      },
      items: [
        'ingestion/fluentd-fluentbit',
        'ingestion/vector',
        'ingestion/splunk-hec',
        'ingestion/open-telemetry',
        'ingestion/elastic-search',
        'ingestion/loki',
      ],
    },
    'logs',
    'dashboards',
    'saved-searches',
    'alerts',
    'minion-searches',
    'cluster-health',
    'retention',
    'contribution-guidelines',
    'community',
  ],
  
};

export default sidebars;
